export {default as Home} from './Home'
export {default as Cart} from './Cart'
export {default as Shop} from './Shop'
export {default as Blog} from './Blog'
export {default as Checkout} from './Checkout'
export {default as ProductDetail} from './ProductDetail'
export {default as BlogDetail} from './BlogDetail'